/* Sega CD diagnostics and combined Sega CD/32X tests. */
#ifndef _SEGACD_H_
#define _SEGACD_H_

#include "types.h"

#define SCD_STATUS_PRESENT     0x0001
#define SCD_STATUS_INITIALIZED 0x0002
#define SCD_STATUS_BUSY        0x0004

enum SegaCDOperation {
	SCD_OP_STATUS = 0,
	SCD_OP_INIT,
	SCD_OP_RESULT0_LO,
	SCD_OP_RESULT0_HI,
	SCD_OP_RESULT1_LO,
	SCD_OP_RESULT1_HI,
	SCD_OP_RESULT2,
	SCD_OP_BIOS_WORD,
	SCD_OP_HINT_TEST,
	SCD_OP_FLAG_TEST,
	SCD_OP_COMM_TEST,
	SCD_OP_PROGRAM_RAM_TEST,
	SCD_OP_WORD_RAM_TEST,
	SCD_OP_MEM_ADDR_HI,
	SCD_OP_MEM_ADDR_LO,
	SCD_OP_MEM_READ_WORD,
	SCD_OP_PCM_RAM_TEST,
	SCD_OP_PCM_CONTROL,
	SCD_OP_DISC_INFO,
	SCD_OP_CDDA_PLAY,
	SCD_OP_CDDA_STOP,
	SCD_OP_DATA_SET_LBA,
	SCD_OP_DATA_START,
	SCD_OP_DATA_POLL,
	SCD_OP_WORD_RAM_READ,
	SCD_OP_WORD_RAM_STRESS,
	SCD_OP_SUBCPU_PING,
	SCD_OP_YM_CONTROL,
	SCD_OP_RESET,
	SCD_OP_MEM_BANK,
	SCD_OP_PCM_RAM_SET,
	SCD_OP_PCM_RAM_COMPARE,
	SCD_OP_TRACK_INFO,
	SCD_OP_TRAY_OPEN,
	SCD_OP_TRAY_CLOSE
};

u16 HwMdSegaCDCommand(u16 operation, u16 argument);
u32 HwMdSegaCDResult0(void);
u32 HwMdSegaCDResult1(void);
u16 HwMdSegaCDResult2(void);

void menu_segacd(void);

#endif
